import Head from "next/head";
import NavBar from "../molecules/navBar";
import { useSession } from "next-auth/react";
import { ToastContainer } from "react-toastify";

interface PageProps {
  title: string;
  children: React.ReactNode;
}

const Page = (props: PageProps) => {
  const { data: session } = useSession();
  const path = session?.user.image;
  if (!path)
    return (
      <>
        <Head>
          <title>{props.title}</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="min-w-screen max-w-screen h-full min-h-screen bg-base-300 text-base-content">
          <NavBar imgPath={""} />
          <div className="">{props.children}</div>
        </div>
        <ToastContainer />
      </>
    );
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-w-screen max-w-screen h-full min-h-screen bg-base-300 text-base-content">
        <NavBar imgPath={path} />
        <div className="">{props.children}</div>
      </div>
      <ToastContainer />
    </>
  );
};

export default Page;
